#CI项目名
name: Release

on: 
  release:
    types: [created]

#CI权限
permissions: write-all

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - name: Show environment
      run: export
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.40
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        build_command: "make"
        binary_name: "tvpxy"
        extra_files: README.md tvpxy
